controller_frequency: 20.0
TrajectoryPlannerROS:

  # Robot Configuration Parameters
  max_vel_x: 0.1
  min_vel_x: 0.05
  max_vel_theta: 0.05
  min_vel_theta: -0.05
  min_in_place_vel_theta: 0.05

  escape_vel: -0.1
  max_rot_vel: 0.05
  min_rot_vel: 0

  acc_lim_x: 0.001
  acc_lim_theta: 0.001
  acc_limit_trans: 0.001

  holonomic_robot: false

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 0.5
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40

  #Trajectory Scoring Parameters
  dwa: true
  heading_scoring: true
  meter_scoring: true
  path distance bias: 32.0
  goal distance bias: 20.0
  occdist scale: 0.02

  # Global plan parameters
  cost factor: 0.55
  neutral cost: 66
  lethal cost: 253

  simple_attractor: true


