controller_frequency: 20.0
TrajectoryPlannerROS:

  # Robot Configuration Parameters
  max_trans_vel: 0.7
  min_trans_vel: 0.1

  max_vel_x: 0.7
  min_vel_x: -0.05

  max_rot_vel: 1.2
  min_rot_vel: 0.2

  acc_lim_x: 1.0
  acc_lim_theta: 2.0
  acc_limit_trans: 2.0

  # Differential-drive robot configuration
  holonomic_robot: false
  acc_lim_y: 0.0
  min_vel_y: 0.0
  max_vel_y: 0.0
  vy_samples: 0

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  # Minimum velocity for the robot to be considered not stop
  trans_stopped_vel: 0.1
  rot_stopped_vel: 0.1

  # Forward Simulation Parameters
  sim_time: 2.0
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  penalize_negative_x: false #no longer used

  #Trajectory Scoring Parameters
  #meter_scoring: true
  path_distance_bias: 32.0
  goal_distance_bias: 9.0
  occdist_scale: 0.020
  stop_time_buffer: 0.5

  # Oscillation prevention parameters
  oscillation_reset_dist: 0.05

  # Global plan parameters
  prune_plan: true

  dwa: false


