footprint: [[-0.3, -0.25], [-0.3, 0.25], [0.3, 0.25], [0.3, -0.25]]
footprint_padding: 0.01

# Радиус оценки стоимости клеток от препятствий + коэфф
inflation radius: 0.55
cost scaling factor: 5.0

# На каком расстоянии ставить препятствия (максимум)
obstacle_range: 5.5
# Максимальная дальность отбрасываемых лучей
raytrace_range: 6.0

observation_sources: laser_scan_sensor
laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}

