obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25], [0.25, -0.25]]
footprint_padding: 0.01
inflation_radius: 0.20

observation_sources: laser_scan_sensor

laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}

