global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  width: 20
  height: 20
  static_map: false
  rolling_window: true
  transform_tolerance: 10
  always_send_full_costmap: false

